# -*- mode: ruby -*-
# vim: set ft=ruby :
USERNAME = "lehakatana"
GLOBAL_VMNAME = "lvm"
GLOBAL_BOXNAME = "centos/7"
GLOBAL_DISK_PATH = "/home/" + USERNAME + "/vmdisks/" + GLOBAL_VMNAME + "/"


ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = GLOBAL_BOXNAME
    config.vm.box_version = "1804.02"
    config.vm.hostname = GLOBAL_VMNAME
    config.vm.network "private_network", ip: "192.168.56.151"
    config.vm.define  GLOBAL_VMNAME
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "4"]
        vb.name = GLOBAL_VMNAME
        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
        i=1
        DISK = (GLOBAL_DISK_PATH + "sata#{i}.vdi")
        vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', "10240"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', i, '--device', 0, '--type', 'hdd', '--medium', DISK]
        i=2
        DISK = (GLOBAL_DISK_PATH + "sata#{i}.vdi")
        vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', "2048"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', i, '--device', 0, '--type', 'hdd', '--medium', DISK]
        i=3
        DISK = (GLOBAL_DISK_PATH + "sata#{i}.vdi")
        vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', "1024"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', i, '--device', 0, '--type', 'hdd', '--medium', DISK]
        i=4
        DISK = (GLOBAL_DISK_PATH + "sata#{i}.vdi")
        vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', "1024"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', i, '--device', 0, '--type', 'hdd', '--medium', DISK]
                 
    end
    config.vm.provision "shell", path:'./provision.sh' 
end

